import { graphql } from "./gql";

/*
  AniList GraphQL documents. Field set is intentionally lean for card grids;
  the detail query pulls the richer fields. All browse queries exclude adult
  content. Types are generated by graphql-codegen (see `npm run codegen`).
*/

export const MediaCardFields = graphql(`
  fragment MediaCardFields on Media {
    id
    title {
      romaji
      english
    }
    coverImage {
      extraLarge
      color
    }
    format
    averageScore
    seasonYear
    genres
    episodes
    nextAiringEpisode {
      episode
      airingAt
      timeUntilAiring
    }
  }
`);

export const HeroFields = graphql(`
  fragment HeroFields on Media {
    id
    title {
      romaji
      english
    }
    bannerImage
    coverImage {
      extraLarge
      color
    }
    description(asHtml: false)
    genres
    format
    nextAiringEpisode {
      episode
      airingAt
      timeUntilAiring
    }
  }
`);

/*
  Hero spotlight: top 8 by popularity among airing shows from the current season
  year only (no fixed score floor — "good" = makes the popular cut for new cours).
*/
export const HomeQuery = graphql(`
  query Home($heroYear: Int!) {
    featured: Page(page: 1, perPage: 8) {
      media(
        status: RELEASING
        seasonYear: $heroYear
        sort: POPULARITY_DESC
        type: ANIME
        isAdult: false
      ) {
        ...HeroFields
      }
    }
    airing: Page(page: 1, perPage: 12) {
      media(
        status: RELEASING
        sort: POPULARITY_DESC
        type: ANIME
        isAdult: false
      ) {
        ...MediaCardFields
      }
    }
    trending: Page(page: 1, perPage: 12) {
      media(sort: TRENDING_DESC, type: ANIME, isAdult: false) {
        ...MediaCardFields
      }
    }
    upcoming: Page(page: 1, perPage: 12) {
      media(
        status: NOT_YET_RELEASED
        sort: POPULARITY_DESC
        type: ANIME
        isAdult: false
      ) {
        ...MediaCardFields
      }
    }
  }
`);

export const AnimeDetailQuery = graphql(`
  query AnimeDetail($id: Int!) {
    Media(id: $id, type: ANIME) {
      id
      title {
        romaji
        english
        native
      }
      description(asHtml: false)
      coverImage {
        extraLarge
        color
      }
      bannerImage
      format
      status
      episodes
      duration
      season
      seasonYear
      averageScore
      meanScore
      popularity
      favourites
      genres
      studios(isMain: true) {
        nodes {
          id
          name
        }
      }
      trailer {
        id
        site
      }
      externalLinks {
        id
        url
        site
      }
      nextAiringEpisode {
        episode
        airingAt
        timeUntilAiring
      }
      relations {
        edges {
          relationType
          node {
            id
            type
            title {
              romaji
            }
            coverImage {
              large
            }
          }
        }
      }
    }
  }
`);

export const BrowseQuery = graphql(`
  query Browse(
    $page: Int = 1
    $sort: [MediaSort] = [POPULARITY_DESC]
    $status: MediaStatus
    $season: MediaSeason
    $seasonYear: Int
    $genre: String
    $format: MediaFormat
    $search: String
  ) {
    Page(page: $page, perPage: 24) {
      pageInfo {
        hasNextPage
        currentPage
      }
      media(
        sort: $sort
        status: $status
        season: $season
        seasonYear: $seasonYear
        genre: $genre
        format: $format
        search: $search
        type: ANIME
        isAdult: false
      ) {
        ...MediaCardFields
      }
    }
  }
`);

/** Newest anime ids for bounded catalog gap-fill (sync script only). */
export const GapFillQuery = graphql(`
  query GapFill($page: Int = 1) {
    Page(page: $page, perPage: 50) {
      media(sort: ID_DESC, type: ANIME, isAdult: false) {
        ...MediaCardFields
      }
    }
  }
`);

export const ScheduleQuery = graphql(`
  query Schedule($start: Int!, $end: Int!, $page: Int = 1) {
    Page(page: $page, perPage: 50) {
      pageInfo {
        hasNextPage
        currentPage
      }
      airingSchedules(
        airingAt_greater: $start
        airingAt_lesser: $end
        sort: TIME
      ) {
        id
        airingAt
        episode
        media {
          id
          title {
            romaji
            english
          }
          coverImage {
            extraLarge
            large
            color
          }
          format
          isAdult
        }
      }
    }
  }
`);
