import { graphql } from "./gql";

/*
  AniList GraphQL documents. Field set is intentionally lean for card grids;
  the detail query pulls the richer fields. All browse queries exclude adult
  content. Types are generated by graphql-codegen (see `npm run codegen`).
*/

export const MediaCardFields = graphql(`
  fragment MediaCardFields on Media {
    id
    title {
      romaji
      english
    }
    coverImage {
      large
      color
    }
    format
    averageScore
    seasonYear
    genres
    episodes
    nextAiringEpisode {
      episode
      airingAt
      timeUntilAiring
    }
  }
`);

export const HomeQuery = graphql(`
  query Home($season: MediaSeason, $seasonYear: Int) {
    trending: Page(page: 1, perPage: 12) {
      media(sort: TRENDING_DESC, type: ANIME, isAdult: false) {
        ...MediaCardFields
      }
    }
    seasonal: Page(page: 1, perPage: 12) {
      media(
        season: $season
        seasonYear: $seasonYear
        sort: POPULARITY_DESC
        type: ANIME
        isAdult: false
      ) {
        ...MediaCardFields
      }
    }
    popular: Page(page: 1, perPage: 12) {
      media(sort: POPULARITY_DESC, type: ANIME, isAdult: false) {
        ...MediaCardFields
      }
    }
  }
`);

export const AnimeDetailQuery = graphql(`
  query AnimeDetail($id: Int!) {
    Media(id: $id, type: ANIME) {
      id
      title {
        romaji
        english
        native
      }
      description(asHtml: false)
      coverImage {
        extraLarge
        color
      }
      bannerImage
      format
      status
      episodes
      duration
      season
      seasonYear
      averageScore
      meanScore
      popularity
      favourites
      genres
      studios(isMain: true) {
        nodes {
          id
          name
        }
      }
      trailer {
        id
        site
      }
      externalLinks {
        id
        url
        site
      }
      nextAiringEpisode {
        episode
        airingAt
        timeUntilAiring
      }
      relations {
        edges {
          relationType
          node {
            id
            type
            title {
              romaji
            }
            coverImage {
              large
            }
          }
        }
      }
    }
  }
`);

export const SeasonQuery = graphql(`
  query Season(
    $season: MediaSeason
    $seasonYear: Int
    $page: Int = 1
    $genres: [String]
    $format: MediaFormat
    $sort: [MediaSort] = [POPULARITY_DESC]
  ) {
    Page(page: $page, perPage: 24) {
      pageInfo {
        hasNextPage
        currentPage
      }
      media(
        season: $season
        seasonYear: $seasonYear
        genre_in: $genres
        format: $format
        sort: $sort
        type: ANIME
        isAdult: false
      ) {
        ...MediaCardFields
      }
    }
  }
`);

export const SearchQuery = graphql(`
  query Search($search: String!, $page: Int = 1) {
    Page(page: $page, perPage: 24) {
      pageInfo {
        hasNextPage
        currentPage
      }
      media(search: $search, type: ANIME, sort: SEARCH_MATCH, isAdult: false) {
        ...MediaCardFields
      }
    }
  }
`);

export const ScheduleQuery = graphql(`
  query Schedule($start: Int!, $end: Int!, $page: Int = 1) {
    Page(page: $page, perPage: 50) {
      pageInfo {
        hasNextPage
        currentPage
      }
      airingSchedules(
        airingAt_greater: $start
        airingAt_lesser: $end
        sort: TIME
      ) {
        id
        airingAt
        episode
        media {
          id
          title {
            romaji
            english
          }
          coverImage {
            large
            color
          }
          format
          isAdult
        }
      }
    }
  }
`);
