/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment MediaCardFields on Media {\n    id\n    title {\n      romaji\n      english\n    }\n    coverImage {\n      large\n      color\n    }\n    format\n    averageScore\n    seasonYear\n    genres\n    episodes\n    nextAiringEpisode {\n      episode\n      airingAt\n      timeUntilAiring\n    }\n  }\n": typeof types.MediaCardFieldsFragmentDoc,
    "\n  query Home {\n    airing: Page(page: 1, perPage: 12) {\n      media(\n        status: RELEASING\n        sort: POPULARITY_DESC\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n    trending: Page(page: 1, perPage: 12) {\n      media(sort: TRENDING_DESC, type: ANIME, isAdult: false) {\n        ...MediaCardFields\n      }\n    }\n    upcoming: Page(page: 1, perPage: 12) {\n      media(\n        status: NOT_YET_RELEASED\n        sort: POPULARITY_DESC\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n  }\n": typeof types.HomeDocument,
    "\n  query AnimeDetail($id: Int!) {\n    Media(id: $id, type: ANIME) {\n      id\n      title {\n        romaji\n        english\n        native\n      }\n      description(asHtml: false)\n      coverImage {\n        extraLarge\n        color\n      }\n      bannerImage\n      format\n      status\n      episodes\n      duration\n      season\n      seasonYear\n      averageScore\n      meanScore\n      popularity\n      favourites\n      genres\n      studios(isMain: true) {\n        nodes {\n          id\n          name\n        }\n      }\n      trailer {\n        id\n        site\n      }\n      externalLinks {\n        id\n        url\n        site\n      }\n      nextAiringEpisode {\n        episode\n        airingAt\n        timeUntilAiring\n      }\n      relations {\n        edges {\n          relationType\n          node {\n            id\n            type\n            title {\n              romaji\n            }\n            coverImage {\n              large\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.AnimeDetailDocument,
    "\n  query Season(\n    $season: MediaSeason\n    $seasonYear: Int\n    $page: Int = 1\n    $genres: [String]\n    $format: MediaFormat\n    $sort: [MediaSort] = [POPULARITY_DESC]\n  ) {\n    Page(page: $page, perPage: 24) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      media(\n        season: $season\n        seasonYear: $seasonYear\n        genre_in: $genres\n        format: $format\n        sort: $sort\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n  }\n": typeof types.SeasonDocument,
    "\n  query Search($search: String!, $page: Int = 1) {\n    Page(page: $page, perPage: 24) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      media(search: $search, type: ANIME, sort: SEARCH_MATCH, isAdult: false) {\n        ...MediaCardFields\n      }\n    }\n  }\n": typeof types.SearchDocument,
    "\n  query Schedule($start: Int!, $end: Int!, $page: Int = 1) {\n    Page(page: $page, perPage: 50) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      airingSchedules(\n        airingAt_greater: $start\n        airingAt_lesser: $end\n        sort: TIME\n      ) {\n        id\n        airingAt\n        episode\n        media {\n          id\n          title {\n            romaji\n            english\n          }\n          coverImage {\n            large\n            color\n          }\n          format\n          isAdult\n        }\n      }\n    }\n  }\n": typeof types.ScheduleDocument,
};
const documents: Documents = {
    "\n  fragment MediaCardFields on Media {\n    id\n    title {\n      romaji\n      english\n    }\n    coverImage {\n      large\n      color\n    }\n    format\n    averageScore\n    seasonYear\n    genres\n    episodes\n    nextAiringEpisode {\n      episode\n      airingAt\n      timeUntilAiring\n    }\n  }\n": types.MediaCardFieldsFragmentDoc,
    "\n  query Home {\n    airing: Page(page: 1, perPage: 12) {\n      media(\n        status: RELEASING\n        sort: POPULARITY_DESC\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n    trending: Page(page: 1, perPage: 12) {\n      media(sort: TRENDING_DESC, type: ANIME, isAdult: false) {\n        ...MediaCardFields\n      }\n    }\n    upcoming: Page(page: 1, perPage: 12) {\n      media(\n        status: NOT_YET_RELEASED\n        sort: POPULARITY_DESC\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n  }\n": types.HomeDocument,
    "\n  query AnimeDetail($id: Int!) {\n    Media(id: $id, type: ANIME) {\n      id\n      title {\n        romaji\n        english\n        native\n      }\n      description(asHtml: false)\n      coverImage {\n        extraLarge\n        color\n      }\n      bannerImage\n      format\n      status\n      episodes\n      duration\n      season\n      seasonYear\n      averageScore\n      meanScore\n      popularity\n      favourites\n      genres\n      studios(isMain: true) {\n        nodes {\n          id\n          name\n        }\n      }\n      trailer {\n        id\n        site\n      }\n      externalLinks {\n        id\n        url\n        site\n      }\n      nextAiringEpisode {\n        episode\n        airingAt\n        timeUntilAiring\n      }\n      relations {\n        edges {\n          relationType\n          node {\n            id\n            type\n            title {\n              romaji\n            }\n            coverImage {\n              large\n            }\n          }\n        }\n      }\n    }\n  }\n": types.AnimeDetailDocument,
    "\n  query Season(\n    $season: MediaSeason\n    $seasonYear: Int\n    $page: Int = 1\n    $genres: [String]\n    $format: MediaFormat\n    $sort: [MediaSort] = [POPULARITY_DESC]\n  ) {\n    Page(page: $page, perPage: 24) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      media(\n        season: $season\n        seasonYear: $seasonYear\n        genre_in: $genres\n        format: $format\n        sort: $sort\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n  }\n": types.SeasonDocument,
    "\n  query Search($search: String!, $page: Int = 1) {\n    Page(page: $page, perPage: 24) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      media(search: $search, type: ANIME, sort: SEARCH_MATCH, isAdult: false) {\n        ...MediaCardFields\n      }\n    }\n  }\n": types.SearchDocument,
    "\n  query Schedule($start: Int!, $end: Int!, $page: Int = 1) {\n    Page(page: $page, perPage: 50) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      airingSchedules(\n        airingAt_greater: $start\n        airingAt_lesser: $end\n        sort: TIME\n      ) {\n        id\n        airingAt\n        episode\n        media {\n          id\n          title {\n            romaji\n            english\n          }\n          coverImage {\n            large\n            color\n          }\n          format\n          isAdult\n        }\n      }\n    }\n  }\n": types.ScheduleDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment MediaCardFields on Media {\n    id\n    title {\n      romaji\n      english\n    }\n    coverImage {\n      large\n      color\n    }\n    format\n    averageScore\n    seasonYear\n    genres\n    episodes\n    nextAiringEpisode {\n      episode\n      airingAt\n      timeUntilAiring\n    }\n  }\n"): typeof import('./graphql').MediaCardFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Home {\n    airing: Page(page: 1, perPage: 12) {\n      media(\n        status: RELEASING\n        sort: POPULARITY_DESC\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n    trending: Page(page: 1, perPage: 12) {\n      media(sort: TRENDING_DESC, type: ANIME, isAdult: false) {\n        ...MediaCardFields\n      }\n    }\n    upcoming: Page(page: 1, perPage: 12) {\n      media(\n        status: NOT_YET_RELEASED\n        sort: POPULARITY_DESC\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n  }\n"): typeof import('./graphql').HomeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AnimeDetail($id: Int!) {\n    Media(id: $id, type: ANIME) {\n      id\n      title {\n        romaji\n        english\n        native\n      }\n      description(asHtml: false)\n      coverImage {\n        extraLarge\n        color\n      }\n      bannerImage\n      format\n      status\n      episodes\n      duration\n      season\n      seasonYear\n      averageScore\n      meanScore\n      popularity\n      favourites\n      genres\n      studios(isMain: true) {\n        nodes {\n          id\n          name\n        }\n      }\n      trailer {\n        id\n        site\n      }\n      externalLinks {\n        id\n        url\n        site\n      }\n      nextAiringEpisode {\n        episode\n        airingAt\n        timeUntilAiring\n      }\n      relations {\n        edges {\n          relationType\n          node {\n            id\n            type\n            title {\n              romaji\n            }\n            coverImage {\n              large\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').AnimeDetailDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Season(\n    $season: MediaSeason\n    $seasonYear: Int\n    $page: Int = 1\n    $genres: [String]\n    $format: MediaFormat\n    $sort: [MediaSort] = [POPULARITY_DESC]\n  ) {\n    Page(page: $page, perPage: 24) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      media(\n        season: $season\n        seasonYear: $seasonYear\n        genre_in: $genres\n        format: $format\n        sort: $sort\n        type: ANIME\n        isAdult: false\n      ) {\n        ...MediaCardFields\n      }\n    }\n  }\n"): typeof import('./graphql').SeasonDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Search($search: String!, $page: Int = 1) {\n    Page(page: $page, perPage: 24) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      media(search: $search, type: ANIME, sort: SEARCH_MATCH, isAdult: false) {\n        ...MediaCardFields\n      }\n    }\n  }\n"): typeof import('./graphql').SearchDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Schedule($start: Int!, $end: Int!, $page: Int = 1) {\n    Page(page: $page, perPage: 50) {\n      pageInfo {\n        hasNextPage\n        currentPage\n      }\n      airingSchedules(\n        airingAt_greater: $start\n        airingAt_lesser: $end\n        sort: TIME\n      ) {\n        id\n        airingAt\n        episode\n        media {\n          id\n          title {\n            romaji\n            english\n          }\n          coverImage {\n            large\n            color\n          }\n          format\n          isAdult\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').ScheduleDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
